# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Make', models.CharField(max_length=264)),
                ('Model', models.CharField(max_length=264)),
                ('Color', models.CharField(max_length=264)),
                ('Year', models.IntegerField(max_length=4)),
                ('Gear', models.CharField(max_length=264)),
                ('Weight', models.IntegerField(max_length=264)),
                ('Fuel', models.CharField(max_length=264)),
                ('Power', models.IntegerField(max_length=264)),
                ('Plate', models.CharField(max_length=16)),
                ('Img', models.ImageField(max_length=264, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=264)),
                ('Username', models.CharField(max_length=264)),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YIDT_app.Owner'),
        ),
    ]
