# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YIDT_app', '0003_auto_20180923_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='images_cars'),
        ),
    ]
