# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YIDT_app', '0004_auto_20180924_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=264)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='Gear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YIDT_app.Gear'),
        ),
        migrations.AlterField(
            model_name='car',
            name='Owner',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='car',
            name='Power',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='Weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='Year',
            field=models.IntegerField(),
        ),
    ]
