# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YIDT_app', '0005_auto_20180924_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Gear',
            field=models.CharField(choices=[('-', '-'), ('Manual', 'MANUAL'), ('Automatic', 'AUTOMATIC')], default='-', max_length=20),
        ),
        migrations.DeleteModel(
            name='Gear',
        ),
    ]
