# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YIDT_app', '0006_auto_20180924_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Fuel',
            field=models.CharField(choices=[('Petrol', 'PETROL'), ('Diesel', 'DIESEL'), ('Electric', 'ELECTRIC'), ('Hybrid', 'HYBRID'), ('Biofuel', 'BIOFUEL')], default='-', max_length=20),
        ),
    ]
