# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YIDT_app', '0007_auto_20180924_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Fuel',
            field=models.CharField(choices=[('-', '-'), ('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('Biofuel', 'Biofuel')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='Gear',
            field=models.CharField(choices=[('-', '-'), ('Manual', 'Manual'), ('Automatic', 'Automatic')], default='-', max_length=20),
        ),
    ]
