# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YIDT_app', '0008_auto_20180924_1558'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
